### ISSUE TITLE
PD Heli Camera Not working

### ISSUE THREAD

**Issue by kschreck0105** [DSRP-Inc/DSRP_Tickets#48] opened 2023-08-06 17:44 UTC
**Reference ticket number:**

**Reporting persons Discord name:**
Rogue205

**Clearly describe the bug:**
Camera in PD Helicopter is not working. 

**Describe the steps to reproduce:**
Get in PD Heli from MRPD and take off. press E (Default bind)  and you should see camera popup

**What is the expected behavior?**
goes into the camera mode

**Screenshots/clips:**

**Comment by Daemon53** [comment] 2023-08-10 22:04
Working

**Comment by shelby0341** [comment] 2023-08-16 05:29
Can confirm is working as intended, moving to completed

**Closed as completed** 2023-08-16 12:25 UTC
Labels: bug, med prio
