### ISSUE TITLE
Transferring Vehicle Charges

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#47] opened 2023-08-06 17:39 UTC
**Reference ticket number:**

**Reporting persons Discord name:**
shelby0341

**Clearly describe the bug:**
When you transfer a car from garage to garage, it costs $2,500. After you transfer it, it only gives you an option to "return and drive" which costs you ANOTHER $2,500 for a total of $5,000 to transfer a vehicle.

**Describe the steps to reproduce:**
Try to transfer a vehicle from garage to garage and pull it out to drive it.

**What is the expected behavior?**
I think it should only be one charge - to transfer it from garage to garage. If it's already in the garage, there should be no reason to "return" it to drive it.

**Screenshots/clips:**

**Comment by PINCH97** [comment] 2023-08-07 15:13
This is not an issue, I will explain how it works

Test 1

- Take car from garage A and you end up losing the car or it poofs 
- Go to the same A garage it originally came from it will cost you $2500 to return it as normal no additional costs

However I feel this is what someone is doing which I have tested and can confirm everything here works as intended.
Test 2

- Take car from garage A and you end up losing the car or it poofs 
- Go to garage B which the car was not originally pulled from and pay $2500 to transfer the car to that garage 
- The car is still in the "Lost" state where its actually in the city they would in return pay additional $2500 to return it
- Because the car has been transferred to garage B all that means is if the server was to restart or they leave and come back another day they will be able to pull the car without paying extra because the database has been refreshed.

**Comment by shelby0341** [comment] 2023-08-07 15:18
It happened to me personally. I drove my car to Sandy and stored it in the Sandy garage. I went on some adventures in a friends truck and was dropped off in Legion Square. I went to transfer the car to Legion from Sandy, and it charged me the $2,500 transfer fee. Once transferred, it then charged me another $2,500 to "return and drive" even though, the car never poofed, the car was never out. It was in the Sandy garage the entire time.

**Comment by shelby0341** [comment] 2023-08-07 15:23
Will try to replicate later today

**Comment by PINCH97** [comment] 2023-08-07 15:26
Changed transfer costs to $500 in case this issue happens here and there to not be as punishing.

**Closed as completed by PINCH97** 2023-08-07 15:26 UTC
Labels: bug

**Comment by shelby0341** [comment] 2023-08-07 23:44
@PINCH97 I tried to replicate it and couldn't either, even restarted the server in between having it at Sandy and transferring it to Legion and still nothing, hopefully it was just a one-off and doesn't come up again.
However thinking about things, I feel like maybe the $500/$2,500 should be reversed? It's kind of like being punished $2,500 if your car poofs if you leave the area as well or server goes down or whatever.
So maybe $2,500 to transfer garages (would promote people to actually go and get their cars instead more) and $500 to retrieve it?
This can be moved to done after though and fingers crossed xD

**Comment by PINCH97** [comment] 2023-08-08 10:42
@shelby0341 Thank you for the Input, that has been amended now so $2500 for transfer and $500 for retrieve/return. Will mark has done now.
