### ISSUE TITLE
PD Hunting notifications

### ISSUE THREAD

**Issue by Daemon53** [DSRP-Inc/DSRP_Tickets#43] opened 2023-08-06 14:47 UTC
PD get sniper rifle shots fire notifications but no blips on locations. Shouldn't get anything at all

**Comment by Daemon53** [comment] 2023-08-11 21:33
I couldn't reproduce this @kschreck0105

**Comment by kschreck0105** [comment] 2023-08-17 01:08
so hunting rifle sets off PD Notification within the hunting area. hunting rifle shouldnt set it off in my opinion

**Comment by Daemon53** [comment] 2023-08-17 21:42
I still can't reproduce. I've made a change. Let's try again.

**Comment by kschreck0105** [comment] 2023-08-17 21:54
I still am not sure what is exactly being tested here

**Comment by shelby0341** [comment] 2023-08-19 22:02
Just tested it and PD does still get notifications for a hunting rifle discharging within the hunting zone. Attached a photo of where Kimo was standing in the hunting area, I had the job of PD and was standing outside of the hunting area.


![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/3d53cd81-ecfe-4e5c-befd-78ba11367471)
![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/b0243a4a-3141-4739-b557-a10b7a4f4885)
![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/f2e361ed-f613-4a3f-83ca-e2700f3d4f13)

**Comment by shelby0341** [comment] 2023-08-20 02:17
Was using the wrong hunting rifle, works as intended with correct one from hunting store. Moving to completed

**Closed as completed** 2023-08-21 04:19 UTC
Labels: bug, low prio
