### ISSUE TITLE
Split inventory shipments for businesses

### ISSUE THREAD

**Issue by Daemon53** [DSRP-Inc/DSRP_Tickets#113] opened 2023-08-15 15:53 UTC

**Comment by Daemon53** [comment] 2023-08-17 20:09
Verify teapot and and pond received two boxes of different ingredients when ordering.

**Comment by shelby0341** [comment] 2023-08-18 01:05
can confirm both places receive two boxes...however...
pond cafe - you cannot order ingredients without enough cash in the business account
little teapot - you can still order ingredients with $0 in the business account

**Comment by Daemon53** [comment] 2023-08-22 20:41
fixed amount check

**Comment by shelby0341** [comment] 2023-08-23 01:19
can confirm is working as intended now "Funds are looking a little low buddy." moving to completed

**Closed as completed** 2023-08-25 02:27 UTC
Labels: enhancement, high prio
